<?php
function visit_api_schema() {
    $schema['visit_api'] = array(
    // Example (partial) specification for table "node".
        'description' => 'The table for the visit api.',
        'fields' => array(
            'id' => array(
                'description' => 'An auto-incremented id.',
                'type' => 'serial',
                'not null' => TRUE,
                'length' => 255,
            ),
            'visit_api_key' => array(
                'description' => 'The visits api key.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'publisher_name' => array(
                'description' => 'The name of the publisher.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
        ),
        'primary key' => array('id'),
);
return $schema;
}