<?php
function visitor_api_schema() {
    $schema['visitor_api'] = array(
    // Example (partial) specification for table "node".
        'description' => 'The table for the visitor api.',
        'fields' => array(
            'id' => array(
                'description' => 'An auto-incremented id.',
                'type' => 'serial',
                'not null' => TRUE,
                'length' => 255,
            ),
            'visitor_api_key' => array(
                'description' => 'The visitor\'s api key.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'visitor_api_url' => array(
                'description' => 'The URL of the Visit API.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'publisher_name' => array(
                'description' => 'The name of the publisher.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
            'publisher_id' => array(
                'description' => 'The id of the publisher.',
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'default' => '',
            ),
        ),
        'primary key' => array('id'),
);
return $schema;
}